spring.datasource.url=jdbc:mysql://localhost:3306/sim_management
spring.datasource.username=root
spring.datasource.password=Ankit@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable DB + JPA completely
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Render port
server.port=${PORT:8081}