spring.datasource.url=jdbc:mysql://localhost:3306/sim_management
spring.datasource.username=root
spring.datasource.password=Ankit@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable DB for Render
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Dynamic port for Render
server.port=${PORT:8081}